### ISSUE TITLE
Error when execute podimo-dl

### ISSUE THREAD

**Issue by BiFl-88** [vincentscode/podimo-dl#3]
Hello,

it seems that I'm to stupid...
I cannot execute the podimo-dl file, because the following error occurs:
\podimo-dl.py", line 1, in <module>
    from gql import gql, Client
ModuleNotFoundError: No module named 'gql'

when I delete some lines in the file to go over in code, other errors occurs :-(

Can you help?

**Comment by vincentscode** [comment]
Hi, it seems your python installation is missing the `gql` package. You can install it by running `pip install "gql[all]"` in your terminal of choice.
